/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.inspection;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.time.*;import java.util.regex.Pattern;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest@AutoConfigureMockMvc class InspectionCoreApiTests{@Autowired MockMvc mvc;static final String HASH="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
 @Test void inspectionClosesOnlyAfterPointsAndHazardsAreVerified()throws Exception{long task=create("INS-CORE-1",2);start(task);point(task,"P-01",true);point(task,"P-02",false);long h=hazard(task,"HZ-CORE-1","CRITICAL");action("/api/core/inspection/hazards/"+h+"/contain","{\"detail\":\"停机并设置警戒区\"}","operator").andExpect(jsonPath("$.data.status").value("CONTAINED"));action("/api/core/inspection/hazards/"+h+"/rectify","{\"rectification\":\"更换部件并完成试运行\",\"evidenceHash\":\""+HASH+"\"}","operator").andExpect(jsonPath("$.data.status").value("RECTIFIED"));action("/api/admin/core/inspection/hazards/"+h+"/verify","{\"approved\":true,\"remark\":\"复核通过\"}","admin").andExpect(jsonPath("$.data.status").value("VERIFIED"));action("/api/admin/core/inspection/tasks/"+task+"/close",null,"admin").andExpect(jsonPath("$.data.status").value("CLOSED"));}
 @Test void incompletePointsBlockTaskClose()throws Exception{long t=create("INS-CORE-2",2);start(t);point(t,"P-01",true);action("/api/admin/core/inspection/tasks/"+t+"/close",null,"admin").andExpect(status().isConflict());}
 @Test void criticalHazardRequiresContainmentBeforeRectification()throws Exception{long t=create("INS-CORE-3",1);start(t);point(t,"P-01",false);long h=hazard(t,"HZ-CORE-3","CRITICAL");action("/api/core/inspection/hazards/"+h+"/rectify","{\"rectification\":\"直接整改\",\"evidenceHash\":\""+HASH+"\"}","operator").andExpect(status().isConflict());}
 @Test void pointSubmissionIsIdempotent()throws Exception{long t=create("INS-CORE-4",1);start(t);point(t,"P-01",true);point(t,"P-01",true);mvc.perform(get("/api/core/inspection/tasks/"+t+"/points").with(httpBasic("operator","operator123"))).andExpect(jsonPath("$.data.length()").value(1));}
 @Test void operatorCannotVerifyHazardOrCloseTask()throws Exception{long t=create("INS-CORE-5",1);start(t);point(t,"P-01",true);action("/api/admin/core/inspection/tasks/"+t+"/close",null,"operator").andExpect(status().isForbidden());}
 private long create(String no,int points)throws Exception{MvcResult r=mvc.perform(post("/api/core/inspection/tasks").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"taskNo\":\""+no+"\",\"planNo\":\"PLAN-01\",\"routeName\":\"生产一线\",\"assignee\":\"巡检员\",\"plannedPoints\":"+points+",\"dueAt\":\""+LocalDateTime.now().plusDays(1)+"\"}")).andExpect(status().isOk()).andReturn();return id(r);}private void start(long id)throws Exception{action("/api/core/inspection/tasks/"+id+"/start",null,"operator").andExpect(status().isOk());}private void point(long id,String code,boolean pass)throws Exception{mvc.perform(post("/api/core/inspection/tasks/"+id+"/points").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"pointCode\":\""+code+"\",\"passed\":"+pass+",\"reading\":\"正常\",\"evidenceHash\":\""+HASH+"\"}")).andExpect(status().isOk());}private long hazard(long task,String no,String risk)throws Exception{MvcResult r=mvc.perform(post("/api/core/inspection/tasks/"+task+"/hazards").with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content("{\"hazardNo\":\""+no+"\",\"title\":\"安全防护异常\",\"riskLevel\":\""+risk+"\",\"owner\":\"设备部\",\"dueDate\":\""+LocalDate.now().plusDays(1)+"\"}")).andExpect(status().isOk()).andReturn();return id(r);}private ResultActions action(String path,String body,String user)throws Exception{var b=post(path).with(httpBasic(user,user.equals("admin")?"admin123":"operator123"));if(body!=null)b.contentType(MediaType.APPLICATION_JSON).content(body);return mvc.perform(b);}private long id(MvcResult r)throws Exception{var m=Pattern.compile("\\\"id\\\":(\\d+)").matcher(r.getResponse().getContentAsString());m.find();return Long.parseLong(m.group(1));}
}
